### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by infacq** [sonnylazuardi/21mobile#2]
``` bash
The following build commands failed:
    Ld build/Build/Intermediates/blitzmobile.build/Debug-iphonesimulator/blitzmobile.build/Objects-normal/i386/blitzmobile normal i386
    Ld build/Build/Intermediates/blitzmobile.build/Debug-iphonesimulator/blitzmobile.build/Objects-normal/x86_64/blitzmobile normal x86_64
(2 failures)
```

**Comment by sonnylazuardi** [comment]
@infacq I've updated the debug configuration can you try again?

**Comment by infacq** [comment]
still same. Do I need to have same environment as you do? I'm developing for IOS

`clang: error: no such file or directory: '/Users/infacq/Documents/21mobile/ios/build/Build/Products/Debug-iphonesimulator/libBVLinearGradient.a'`

**Comment by sonnylazuardi** [comment]
@infacq I think  you need to add it manually `libBVLinearGradient.a` to xcode
